// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJNXteIYhd2ullKqXHnlzQclyfmdvSty4',
    appId: '1:1092058989273:web:eb5943b68ea7e4908274c8',
    messagingSenderId: '1092058989273',
    projectId: 'airbnb-clone-ab82f',
    authDomain: 'airbnb-clone-ab82f.firebaseapp.com',
    storageBucket: 'airbnb-clone-ab82f.appspot.com',
    measurementId: 'G-TZSMDV87GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIfbxlAbQPKfAstgFzt64VIJbe_a8zeY',
    appId: '1:1092058989273:android:da7bd4aef3ee03038274c8',
    messagingSenderId: '1092058989273',
    projectId: 'airbnb-clone-ab82f',
    storageBucket: 'airbnb-clone-ab82f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOUZRQ-HF2WqlgKy3WreTP_YP07o05oY4',
    appId: '1:1092058989273:ios:b78e6c06116d600d8274c8',
    messagingSenderId: '1092058989273',
    projectId: 'airbnb-clone-ab82f',
    storageBucket: 'airbnb-clone-ab82f.appspot.com',
    iosBundleId: 'com.example.airbnbClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOUZRQ-HF2WqlgKy3WreTP_YP07o05oY4',
    appId: '1:1092058989273:ios:ac15ca2d85da3f428274c8',
    messagingSenderId: '1092058989273',
    projectId: 'airbnb-clone-ab82f',
    storageBucket: 'airbnb-clone-ab82f.appspot.com',
    iosBundleId: 'com.example.airbnbClone.RunnerTests',
  );
}
